config/routes.rb
Rails.application.routes.draw do
  get 'top/index'

  resources :posts, only: [:index,:new,:create,:edit,:update,:destroy] 
  root 'posts#index'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    :sessions => 'users/sessions'
  }

  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :content, presence: true , length: { maximum: 140 }
    
    belongs_to :user
    
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  
  mount_uploader :avatar, AvatarUploader #deviseの設定配下に追記
  
  has_many :posts
  
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end
  
  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end
  
  def self.create_unique_string
    SecureRandom.uuid
  end
  
  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

   PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @posts = Post.all
  end

  def new
    if params[:back]
      @post = Post.new(posts_params)
    else
      @post = Post.new
    end
  end
  
  
  def create
    @post = Post.new(posts_params)
    @post.user_id = current_user.id
    #Post.create(posts_params)
    if @post.save
      redirect_to posts_path, notice: "投稿しました！"
      #NoticeMailer.sendmail_blog(@post).deliver
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(posts_params)
    redirect_to posts_path, notice: "編集しました！"
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "削除しました！"
  end
  
  private
  def posts_params
     params.require(:post).permit(:title, :content, :image, :image_cache)
  end
  
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def new
    super
  end

  # def new
  #   self.resource = resource_class.new(sign_in_params)
  #   clean_up_passwords(resource)
  #   #yield resource if block_given?
  #   #render 'devise/sessions/new'
  #   render 'top/index'
    
  #   #redirect_to 'top/index'
  #   #clean_up_passwordss(resource)
  #   #yield resource if block_given?
  #   #respond_with(resource, serialize_options(resource))
   
  # end
  
  def new
    self.resource = resource_class.new(sign_in_params)
    logger.debug("SSSSSSSSSSSSSSSSS" + "ssss")
    logger.debug(resource)
    clean_up_passwords(resource)
    yield resource if block_given?
    respond_with(resource, serialize_options(resource))
  end
  
  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { methods: methods, only: [:password] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 省略
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?
    
    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end

  def profile_img(post)
    return image_tag(post.avatar, alt: post.name) if post.avatar?
    
    unless post.provider.blank?
      img_url = post.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: post.name)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Achieve</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>  
    <ul>
      <% if user_signed_in? %>
        <li><%= link_to 'マイページ', edit_user_registration_path %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path  %></li>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
      <% end %>
        <li class = 'rightPos'><%= link_to '投稿', new_post_path %></li>
    </ul>
  </header>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
    <%= form_for(@post) do |f| %>
        <% if @post.errors.any? %>
            <div id="error_explanation">
              <h2><%= @post.errors.count %>件のエラーがあります。</h2>
              <ul>
              <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
         <% end %>

      <%= f.label :picture %>
      <%= image_tag @post.image.url if @post.image? %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
      
      <%= f.label :content %>
      <%= f.text_area :content , class: 'form-control'%>
      <br>
      <%= f.submit '投稿', class: 'btn btn-primary btn-block'  %>
      <br>
      <%= link_to "投稿一覧画面にもどる", posts_path %>

    <% end %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    ■編集
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

    
    <p><%= notice %></p>

<!--%= link_to "つぶやく", new_post_path %-->

<!--h1>ツイート一覧</h1-->

<% @posts.each do |post| %>
  <%= profile_img(post.user) if profile_img(post.user) %>
  <p>投稿者：<%= post.user.name %></p>
  
  <% if post.image? %>
 　　　 <%= image_tag(post.image) %>
　<% end %>
  <p>本文:<%= post.content %></p>
  <%= Time.now.strftime("%Y年%m月%d日 %H時%M分") %>
  <br>
  <%= link_to "編集", edit_post_path(post.id), class: 'btn btn-default btn-sm btn-success'  %>
  
  <%= link_to "削除", post_path(post.id), method: :delete,data: { confirm: '本当に削除していいですか？' }, class: 'btn btn-default btn-sm btn btn-danger'  %>
  <p>------------------------------------------------  </p>
<% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    ■投稿内容
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<div class="container">
  <div class="wrapper col-md-4 col-md-offset-4 col-sm-10">
    <h2>ログイン</h2>

    <%= "本人確認用のメールがあなたのEメールアドレスに送られました。メール内のリンクからアカウントを有効化させてください。" %>

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>

      <div class="field">
        <%= f.email_field :email, autofocus: true, class: "form-control", placeholder: "メールアドレス" %>
      </div>

      <div class="field">
        <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "パスワード" %>
      </div>

      <% if devise_mapping.rememberable? %>
        <div class="field">
          <%= f.check_box :remember_me %>
          <%= f.label :内容を記憶させる %>
        </div>
      <% end %>

      <div class="actions">
        <%= f.submit "ログイン", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>

    <%= render "devise/shared/links" %>

  </div>
</div>